version: '3.8'

services:
  # Python application
  app:
    build: .
    container_name: logging-app
    environment:
      - NAME_APP=you-can-do-it
    depends_on:
      - loki
    labels:
      logging: "promtail"
      logging_jobname: "ycdi"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app_logging

  app2:
    build: .
    container_name: logging-app-2
    environment:
      - NAME_APP=learn-management-system
    depends_on:
      - loki
    labels:
      logging: "promtail"
      logging_jobname: "lms"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app_logging

  # Loki for log aggregation
  loki:
    image: grafana/loki:3.5
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    networks:
      - app_logging

  # Promtail for log shipping
  promtail:
    image: grafana/promtail:3.5
    container_name: promtail
    volumes:
      - ./config/promtail-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - app_logging

  # Grafana for visualization
  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./config/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki
    networks:
      - app_logging

volumes:
  loki-data:
  grafana-data:

networks:
  app_logging:
    driver: bridge