{
 "title": "logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "Instruction",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Instruction\n\n**Clicking** a pie chart (`Level Log Distribution`) segment will filter the dashboard to show only that category's data."
   }
  },
  {
   "title": "Method Distribution ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({namespace=\"python-logging-loki\"} |= `$filter` | logfmt | method =~ `.+` [$__range]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Level Log Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=\"python-logging-loki\"} |= `$filter` | logfmt | level =~ `.+` [$__range]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Path Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(path) (count_over_time({namespace=\"python-logging-loki\"} |= `$filter` | logfmt | path =~ `.+` [$__range])))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Method Distribution Auth Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({container=\"auth-service\"} |= `$filter` | logfmt | method =~ `.+` [$__range]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Method Distribution LMS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({container=\"learn-management-system\"} |= `$filter` | logfmt | method =~ `.+` [$__range]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Path Distribution Top 10",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "topk(10, sum by(path, level, method) (count_over_time({namespace=\"python-logging-loki\"} |= `$filter` | logfmt [$__range])))"
    }
   ]
  },
  {
   "title": "Raw Logs LMS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{container=\"auth-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Raw Logs Auth Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "{container=\"auth-service\"} |= ``"
    }
   ]
  }
 ]
}